name: deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Deploy to server using rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /var/www/faceit-checker/backend/dist
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to package.json and yarn.lock
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: package.json yarn.lock
          remote_path: /var/www/faceit-checker/backend
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Install dependencies on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/faceit-checker/backend
            yarn install --frozen-lockfile --production

      - name: Restart application with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/
            pm2 restart faceit-checker-backend || pm2 start ecosystem.config.js

