name: deploy
on:
  push:
    branches:
      - master

env:
  DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
  DEPLOY_DIST_DIR: ${{ secrets.DEPLOY_DIST_DIR }}
  DEPLOY_ECO_DIR: ${{ secrets.DEPLOY_ECO_DIR }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Deploy to server using rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: $DEPLOY_DIST_DIR
          remote_host: $DEPLOY_HOST
          remote_user: $DEPLOY_USER
          remote_key: $DEPLOY_SSH_KEY

      - name: Deploying package.json and yarn.lock to server
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: package.json yarn.lock
          remote_path: $DEPLOY_DIR
          remote_host: $DEPLOY_HOST
          remote_user: $DEPLOY_USER
          remote_key: $DEPLOY_SSH_KEY

      - name: Install dependencies on server
        run: |
          echo "$DEPLOY_SSH_KEY" > /tmp/deploy_key.pem
          chmod 600 /tmp/deploy_key.pem
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            which node
            cd $DEPLOY_DIR
            yarn install --frozen-lockfile
          EOF

      - name: Restart application with PM2
        run: |
          echo "$DEPLOY_SSH_KEY" > /tmp/deploy_key.pem
          chmod 600 /tmp/deploy_key.pem
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            cd $DEPLOY_ECO_DIR
            pm2 restart faceit-checker-backend || pm2 start ./ecosystem.config.js
          EOF
